<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TournamentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'name' => 'Unknown'],
            ['id' => 2, 'name' => 'Gambits Cup Throwback RA-LA PD'],
            ['id' => 3, 'name' => 'SC: Brood War ROG GAME ON 1on1 - #4 CZSK'],
            ['id' => 4, 'name' => 'Zotac Cup NA/SA'],
            ['id' => 5, 'name' => 'OSC SC:R SEA Weekly #7'],
            ['id' => 6, 'name' => 'OSC SC:R Open #6'],
            ['id' => 7, 'name' => 'Pan-American Team League S1W5'],
            ['id' => 8, 'name' => 'Clan SK Tourney @ US East 10/06/17'],
            ['id' => 9, 'name' => 'Clash for Char #6'],
            ['id' => 10, 'name' => 'TL Open #1'],
            ['id' => 11, 'name' => 'Michael vs Bonyth Showmatch'],
            ['id' => 12, 'name' => 'Blacer War I'],
            ['id' => 13, 'name' => 'SC:R Italian Esports Open 2017 - Qualifi'],
            ['id' => 14, 'name' => 'Pan-American Team League S1W6'],
            ['id' => 15, 'name' => 'OSC SC:R SEA Weekly #8'],
            ['id' => 16, 'name' => 'Clan SK Tourney @ US East 10/13/17'],
            ['id' => 17, 'name' => 'Rox.Dewalt vs  cSc.Brat_OK Showmatch'],
            ['id' => 18, 'name' => 'OSC SC:R Open #7'],
            ['id' => 19, 'name' => 'SC Remastered Cup #9 Europe'],
            ['id' => 20, 'name' => 'TL Open #2'],
            ['id' => 21, 'name' => 'Zotac Cup Masters: SCR North America Qua'],
            ['id' => 22, 'name' => 'ZOTAC CUP MASTERS: SCR SOUTH AMERICA QUA'],
            ['id' => 23, 'name' => 'Italian Esports Open - Playoffs - Europe'],
            ['id' => 24, 'name' => 'OSC SC:R SEA Weekly #9'],
            ['id' => 25, 'name' => 'Clan SK Tourney @ US East 10/20/17'],
            ['id' => 26, 'name' => 'Zotac Cup Masters: SCR North America Qualifier #2'],
            ['id' => 27, 'name' => 'ESL SC Remastered Cup #10 Europe'],
            ['id' => 28, 'name' => 'TL Open #3'],
            ['id' => 29, 'name' => 'Rus Brain Cup S1: Round 1'],
            ['id' => 30, 'name' => 'Clash for Char #7'],
            ['id' => 31, 'name' => 'OSC SC:R SEA Weekly #10'],
            ['id' => 32, 'name' => 'BSL3 Showmatch'],
            ['id' => 33, 'name' => 'OSC SC:R Open #8'],
            ['id' => 34, 'name' => 'ESL SC Remastered Cup #11 Europe'],
            ['id' => 35, 'name' => 'TL Open #4'],
            ['id' => 36, 'name' => 'Rus Brain Cup S1: Round 2'],
            ['id' => 37, 'name' => 'Clash for Char #8'],
            ['id' => 38, 'name' => 'Italian Esports Open Lucca Finals'],
            ['id' => 39, 'name' => 'OSC SC:R Open #9'],
            ['id' => 40, 'name' => 'Rus Brain Cup S1: Round 3'],
            ['id' => 41, 'name' => 'Clash for Char #9'],
            ['id' => 42, 'name' => 'ESL SC Remastered Cup #12 Europe'],
            ['id' => 43, 'name' => 'TL Open #5'],
            ['id' => 44, 'name' => 'Zotac Cup Masters: SCR North America Qualifier #3'],
            ['id' => 45, 'name' => 'Clan SK Weekly 11/10/17'],
            ['id' => 46, 'name' => 'Rus Brain Cup S1: Round 4'],
            ['id' => 47, 'name' => 'Clash for Char #10'],
            ['id' => 48, 'name' => 'OSC SC:R Open #10'],
            ['id' => 49, 'name' => 'Gambit Cup Guilded.gg WB final / LB Final'],
            ['id' => 50, 'name' => 'Clan SK Tourney @ US East 11/17/17'],
            ['id' => 51, 'name' => '11/18 Saturday ZOTAC Cup Global'],
            ['id' => 52, 'name' => 'TL Open #6'],
            ['id' => 53, 'name' => 'ESL SC Remastered Cup #13 Europe'],
            ['id' => 54, 'name' => 'Zotac Cup Masters: SCR North America Qualifier #4'],
            ['id' => 55, 'name' => 'Clash for Char #11'],
            ['id' => 56, 'name' => 'Rus Brain Cup S1: Round 5'],
            ['id' => 57, 'name' => 'Gambit Cup Guilded.gg Grand Final'],
            ['id' => 58, 'name' => 'Clan SK Tourney @ US East 11/24/17'],
            ['id' => 59, 'name' => 'SC Remastered Cup #14 Europe'],
            ['id' => 60, 'name' => 'TL Open #7'],
            ['id' => 61, 'name' => 'Rus Brain Cup S1: Round 6'],
            ['id' => 62, 'name' => 'The Clash for Char #12'],
            ['id' => 63, 'name' => 'The Clash for Char Showmatch #1'],
            ['id' => 64, 'name' => 'Clan SK Tourney @ US East 12/01/17'],
            ['id' => 65, 'name' => 'OSC SC:R Open #11'],
            ['id' => 66, 'name' => 'SC Remastered Cup #15 Europe'],
            ['id' => 67, 'name' => 'ZOTAC CUP Masters: StarCraft Remastered'],
            ['id' => 68, 'name' => 'Rus Brain Cup S1: Round 7'],
            ['id' => 69, 'name' => 'ZOTAC CUP Masters SCRM/Showmatch'],
            ['id' => 70, 'name' => 'OSC SC:R Open #12'],
            ['id' => 71, 'name' => 'Rus Brain Cup S1: Decider'],
            ['id' => 72, 'name' => 'Rus Brain Cup S1: Playoffs [Main Event]'],
            ['id' => 73, 'name' => 'Twitch Starcraft Holiday Bash'],
            ['id' => 74, 'name' => 'OSC SC:R Open #13'],
            ['id' => 75, 'name' => 'Clan SK Tourney @ US East 12/22/17'],
            ['id' => 76, 'name' => 'Clash for Christmas'],
            ['id' => 77, 'name' => 'Bombastic StarLeague3 Qualify#1'],
            ['id' => 78, 'name' => 'OSC SC:R Open #14'],
            ['id' => 79, 'name' => 'Bombastic StarLeague3 Qualify#2'],
            ['id' => 80, 'name' => 'Clash for Char #14'],
            ['id' => 81, 'name' => 'Bombastic StarLeague 3 Finals'],
            ['id' => 82, 'name' => 'Clash for Char #15 - Single Elim Tournament'],
            ['id' => 83, 'name' => 'BSL4 King of the Hill 01.02.2018'],
            ['id' => 84, 'name' => 'BSL Pro #1'],
            ['id' => 85, 'name' => 'BSL4 King of the Hill 08.02.2018'],
            ['id' => 86, 'name' => 'BSL Pro #2'],
            ['id' => 87, 'name' => 'BSL 4 PRO #3'],
            ['id' => 88, 'name' => 'The Clash for Char #16'],
            ['id' => 89, 'name' => 'BSL 4 KOTH FEBRUARY22'],
            ['id' => 90, 'name' => 'BSL PRO #4'],
            ['id' => 91, 'name' => 'BSL4 Swiss Tournament R1'],
            ['id' => 92, 'name' => 'BSL4 Swiss Tournament R2'],
            ['id' => 93, 'name' => 'STPL Season 1 Round 1 GroupStage'],
            ['id' => 94, 'name' => 'Have At You! #12'],
            ['id' => 95, 'name' => 'StarCraft: Remastered Pro Series Qualifier 1'],
            ['id' => 96, 'name' => 'BSL4 Swiss Tournament  r3'],
            ['id' => 97, 'name' => 'BSL4 Swiss Tournament  r4'],
            ['id' => 98, 'name' => 'Have At You! #13'],
            ['id' => 99, 'name' => 'BSL4 Swiss Tournament  r5'],
            ['id' => 100, 'name' => 'BSL4 Swiss Tournament  r6'],
            ['id' => 101, 'name' => 'Have At You #14'],
            ['id' => 102, 'name' => 'BSL4 Swiss Tournament  r7'],
            ['id' => 103, 'name' => 'BSL4 Group A'],
            ['id' => 104, 'name' => 'MOSCOW  Old School LAN'],
            ['id' => 105, 'name' => 'BSL4 Group B'],
            ['id' => 106, 'name' => 'BSL Race Wars #1'],
            ['id' => 107, 'name' => 'BSL4 Group C'],
            ['id' => 108, 'name' => 'FBW Cup #1'],
            ['id' => 109, 'name' => 'BSL4 Group D'],
            ['id' => 110, 'name' => 'Card Cup Week 1'],
            ['id' => 111, 'name' => 'BSL Race Wars #2'],
            ['id' => 112, 'name' => 'STPL Season 1 Round 1 PlayOffs'],
            ['id' => 113, 'name' => 'Have At You #15'],
            ['id' => 114, 'name' => 'Card Cup Week 2'],
            ['id' => 115, 'name' => 'BSL Race Wars #3'],
            ['id' => 116, 'name' => 'BSL4 RO8'],
            ['id' => 117, 'name' => 'Card Cup Week 3'],
            ['id' => 118, 'name' => 'BSL4 SEMIFINALS RO4'],
            ['id' => 119, 'name' => 'Have At You #16'],
            ['id' => 120, 'name' => 'Card Cup Week 4'],
            ['id' => 121, 'name' => 'BSL4 FINALS AND 3RD'],
            ['id' => 122, 'name' => 'STPL Season 1 Round 2 GroupStage'],
            ['id' => 123, 'name' => 'Card Cup Week 5'],
            ['id' => 124, 'name' => 'Have At You #17'],
            ['id' => 125, 'name' => 'Card Cup Week 6'],
            ['id' => 126, 'name' => 'Biohazard Super Cup Q1'],
            ['id' => 127, 'name' => 'Biohazard Super Cup Q2'],
            ['id' => 128, 'name' => 'Card Cup Week 7'],
            ['id' => 129, 'name' => 'Biohazard Super Cup Q3'],
            ['id' => 130, 'name' => 'Biohazard Super Cup Q4'],
            ['id' => 131, 'name' => 'Have At You #18'],
            ['id' => 132, 'name' => 'Biohazard Super Cup Q5'],
            ['id' => 133, 'name' => 'Biohazard Super Cup Q6'],
            ['id' => 134, 'name' => 'BSL CONTINENTS WAR EU VS NA D1'],
            ['id' => 135, 'name' => 'BSL CONTINENTS WAR EU VS NA D2'],
            ['id' => 136, 'name' => 'Have At You #19'],
            ['id' => 137, 'name' => 'The Brood War Life Tournament 1'],
            ['id' => 138, 'name' => 'The Brood War Life Tournament 2'],
            ['id' => 139, 'name' => 'Biohazard Super Cup Q7'],
            ['id' => 140, 'name' => 'Biohazard Super Cup Q8'],
            ['id' => 141, 'name' => 'StarCraft: Remastered Pro Series Qualifier 2'],
            ['id' => 142, 'name' => 'StarCraft: Remastered Pro Series Qualifier 3'],
            ['id' => 143, 'name' => 'The Brood War Life Tournament 3'],
            ['id' => 144, 'name' => 'StarLadder Pro Series Ro16Swiss  R1'],
            ['id' => 145, 'name' => 'NA Team Battle '],
            ['id' => 146, 'name' => 'Road to Moscow: StarCraft Remastered Cup'],
            ['id' => 147, 'name' => 'StarLadder Pro Series Ro16Swiss  R2'],
            ['id' => 148, 'name' => 'StarLadder Pro Series Swiss Round 3'],
            ['id' => 149, 'name' => 'Biohazard Super Cup final event'],
            ['id' => 150, 'name' => 'RCC - The Arena Week 20'],
            ['id' => 151, 'name' => 'StarLadder Pro Series Swiss Round 4'],
            ['id' => 152, 'name' => 'STPL Season 1 Round 2 PlayOffs'],
            ['id' => 153, 'name' => 'StarLadder Pro Series Swiss Round 5'],
            ['id' => 154, 'name' => 'StarLadder Pro Series playoffs'],
            ['id' => 155, 'name' => 'Have At You 20'],
            ['id' => 156, 'name' => 'BSL5 RO24 GROUP D'],
            ['id' => 157, 'name' => 'BWCL SEASON 46 WEEK 1'],
            ['id' => 158, 'name' => 'StarLadder Pro Series Finals'],
            ['id' => 159, 'name' => 'BWCL SEASON 46 WEEK 2'],
            ['id' => 160, 'name' => 'Have At You 21'],
            ['id' => 161, 'name' => 'BWCL SEASON 46 WEEK 3'],
            ['id' => 162, 'name' => 'STPL Season 1 Round 3 GroupStage'],
            ['id' => 163, 'name' => 'BSL CONTINENTS BATTLES 2 NA VS SA'],
            ['id' => 164, 'name' => 'BWCL SEASON 46 WEEK 4'],
            ['id' => 165, 'name' => 'Have At You 22'],
            ['id' => 166, 'name' => 'BWCL SEASON 46 WEEK 5'],
            ['id' => 167, 'name' => 'NA Battle 3'],
            ['id' => 168, 'name' => 'BWCL SEASON 46 WEEK 6'],
            ['id' => 169, 'name' => 'BSL5 Ladder Tour 1'],
            ['id' => 170, 'name' => 'InfoCraft.pl LAN 1'],
            ['id' => 171, 'name' => 'Have At You 23'],
            ['id' => 172, 'name' => 'BSL5_Ladder_Tournament_2'],
            ['id' => 173, 'name' => 'BSL5_Ladder_Tournament_3'],
            ['id' => 174, 'name' => 'BSL5 King of the Hill October 30 2018'],
            ['id' => 175, 'name' => 'BSL5 RO24 GROUP E'],
            ['id' => 176, 'name' => 'Brood_War_20th_Anniversary_LAN'],
            ['id' => 177, 'name' => 'BSL5 RO24 GROUP C'],
            ['id' => 178, 'name' => 'Have At You 24'],
            ['id' => 179, 'name' => 'BSL5 RO24 GROUP F'],
            ['id' => 180, 'name' => 'BSL5 RO64 CHOBOLEAGUE'],
            ['id' => 181, 'name' => 'BSL5 RO24 GROUP A'],
            ['id' => 182, 'name' => 'BSL5 RO24 GROUP B'],
            ['id' => 183, 'name' => 'BSL5 RO16 CHOBOLEAGUE GROUP A'],
            ['id' => 184, 'name' => 'BSL5 RO16 CHOBOLEAGUE GROUP C'],
            ['id' => 185, 'name' => 'Defiler Tour 84'],
            ['id' => 186, 'name' => 'BSL5 Ro16 GROUP A'],
            ['id' => 187, 'name' => 'Have At You 25'],
            ['id' => 188, 'name' => 'BSL5 Ro16 GROUP C'],
            ['id' => 189, 'name' => 'BSL5 RO16 CHOBOLEAGUE GROUP B'],
            ['id' => 190, 'name' => 'BSL5 RO16 CHOBOLEAGUE GROUP D'],
            ['id' => 191, 'name' => 'NA vs. EU Showmatch - Lumire vs. LancerX'],
            ['id' => 192, 'name' => 'ThornCraft  1'],
            ['id' => 193, 'name' => 'BSL5 Ro16 GROUP D'],
            ['id' => 194, 'name' => 'BSL5 Ro16 GROUP B'],
            ['id' => 195, 'name' => 'STPL Season 1 Round 3 PlayOffs'],
            ['id' => 196, 'name' => 'BLS5 RO8 CHOBOLEAGUE'],
            ['id' => 197, 'name' => 'BSL5 RO8 D1'],
            ['id' => 198, 'name' => 'BLS5 SEMIFINALS CHOBOLEAGUE'],
            ['id' => 199, 'name' => 'BSL5 RO8 D2'],
            ['id' => 200, 'name' => 'Defiler Tour 85'],
            ['id' => 201, 'name' => 'BSL5 SEMIFINALS'],
            ['id' => 202, 'name' => 'BSL5  FINALS'],
            ['id' => 203, 'name' => 'BLS5 FINALS CHOBOLEAGUE'],
            ['id' => 204, 'name' => 'Have At You 26'],
            ['id' => 205, 'name' => 'RCC - The Arena Week 21 ASL Edition'],
            ['id' => 206, 'name' => 'BSL6 Ladder Tournament 1'],
            ['id' => 207, 'name' => 'BW Jeez weekly 1'],
            ['id' => 208, 'name' => 'BSL6 Ladder Tournament 2'],
            ['id' => 209, 'name' => 'LETS GO'],
            ['id' => 210, 'name' => 'BW Jeez weekly 2'],
            ['id' => 211, 'name' => 'Have At You 27'],
            ['id' => 212, 'name' => 'BSL6 Ladder Tournament 3'],
            ['id' => 213, 'name' => 'BW Jeez weekly 3'],
            ['id' => 214, 'name' => 'BWCL S47 W1'],
            ['id' => 215, 'name' => 'BSL6 Nation Wars'],
            ['id' => 216, 'name' => 'EGM Fight Night 1'],
            ['id' => 217, 'name' => 'BW Jeez weekly 4'],
            ['id' => 218, 'name' => 'BWCL S47 W2'],
            ['id' => 219, 'name' => 'BSL6 RO24 GROUP A PROLEAGUE'],
            ['id' => 220, 'name' => 'BSL6 RO32 GROUPS GOSULEAGUE'],
            ['id' => 221, 'name' => 'BSL6 CHOBOLEAGUE RO32'],
            ['id' => 222, 'name' => 'BSL6 CHOBOLEAGUE Ro32 Tie breaker'],
            ['id' => 223, 'name' => 'BWCL S47 W3'],
            ['id' => 224, 'name' => 'BW Jeez weekly 5'],
            ['id' => 225, 'name' => 'BSL6 RO24 GROUP C PROLEAGUE'],
            ['id' => 226, 'name' => 'Have At You 28'],
            ['id' => 227, 'name' => 'BSL6 RO24 GROUP B PROLEAGUE'],
            ['id' => 228, 'name' => 'BWCL  S47 W4'],
            ['id' => 229, 'name' => 'BW Jeez weekly 6'],
            ['id' => 230, 'name' => 'STPL Season 1 Round 4 GroupStage'],
            ['id' => 231, 'name' => 'BSL6 RO24 GROUP D PROLEAGUE'],
            ['id' => 232, 'name' => 'BWCL S47 W5'],
            ['id' => 233, 'name' => 'BW Jeez weekly 7'],
            ['id' => 234, 'name' => 'BSL6 RO24 GROUP E PROLEAGUE'],
            ['id' => 235, 'name' => 'BSL6 RO24 GROUP F PROLEAGUE'],
            ['id' => 236, 'name' => 'Defiler Tour 86'],
            ['id' => 237, 'name' => 'EGM Fight Night 2'],
            ['id' => 238, 'name' => 'Parabola tournament 1'],
            ['id' => 239, 'name' => 'BSL6 CHOBOLEAGUE RO16'],
            ['id' => 240, 'name' => 'BWCL S47 W6'],
            ['id' => 241, 'name' => 'BW Jeez weekly 8'],
            ['id' => 242, 'name' => 'BSL6 RO16 GROUP A GOSULEAGUE'],
            ['id' => 243, 'name' => 'BSL6 RO16 GROUP B GOSULEAGUE'],
            ['id' => 244, 'name' => 'BSL6 RO16 GROUP A PROLEAGUE'],
            ['id' => 245, 'name' => 'BSL6 CHOBOLEAGUE RO8'],
            ['id' => 246, 'name' => 'BWCL S47 W7'],
            ['id' => 247, 'name' => 'BW Jeez weekly 9'],
            ['id' => 248, 'name' => 'BSL6 RO16 GROUP B PROLEAGUE'],
            ['id' => 249, 'name' => 'BSL6 RO16 GROUP C GOSULEAGUE'],
            ['id' => 250, 'name' => 'BSL6 RO16 GROUP D GOSULEAGUE'],
            ['id' => 251, 'name' => 'BSL6 RO16 GROUP C PROLEAGUE'],
            ['id' => 252, 'name' => 'BWCL S47 W8'],
            ['id' => 253, 'name' => 'BW Jeez weekly 10'],
            ['id' => 254, 'name' => 'BSL6 RO16 GROUP D PROLEAGUE'],
            ['id' => 255, 'name' => 'BSL6 RO8 GOSULEAGUE'],
            ['id' => 256, 'name' => 'BSL 6 PROLEAGUE RO8 D1'],
            ['id' => 257, 'name' => 'BSL6 CHOBOLEAGUE RO4'],
            ['id' => 258, 'name' => 'BWCL S47 W9'],
            ['id' => 259, 'name' => 'BW Jeez weekly 11'],
            ['id' => 260, 'name' => 'BSL 6 PROLEAGUE RO8 D2'],
            ['id' => 261, 'name' => 'BSL6 RO4 GOSULEAGUE'],
            ['id' => 262, 'name' => 'BSL 6 PROLEAGUE SEMIFINALS'],
            ['id' => 263, 'name' => 'BW Jeez weekly 12'],
            ['id' => 264, 'name' => 'BWCL S47 W10'],
            ['id' => 265, 'name' => 'BWCL Season 47 Playoffs'],
            ['id' => 266, 'name' => 'BSL 6 PROLEAGUE FINALS'],
            ['id' => 267, 'name' => 'BSL6 FINALS GOSULEAGUE'],
            ['id' => 268, 'name' => 'BSL6 CHOBOLEAGUE FINALS'],
            ['id' => 269, 'name' => 'Defiler Russian Tour 2019'],
            ['id' => 270, 'name' => 'EGM Fight Night 3'],
            ['id' => 271, 'name' => 'BW Jeez weekly 13'],
            ['id' => 272, 'name' => 'BW Jeez weekly 14'],
            ['id' => 273, 'name' => 'BWCL PLAYOFFS Q219'],
            ['id' => 274, 'name' => 'EGM Fight Night 4 AfreecaTV'],
            ['id' => 275, 'name' => 'BW Jeez weekly 15'],
            ['id' => 276, 'name' => 'Lets Go 2'],
            ['id' => 277, 'name' => 'BW Jeez weekly 16'],
            ['id' => 278, 'name' => 'BW Jeez weekly 17'],
            ['id' => 279, 'name' => 'Lets Go 3'],
            ['id' => 280, 'name' => 'BW Jeez weekly 18'],
            ['id' => 281, 'name' => 'King of Kings - 300 Special Edition'],
            ['id' => 282, 'name' => 'BW Jeez weekly 19'],
            ['id' => 283, 'name' => 'Defiler Mega Tour'],
            ['id' => 284, 'name' => 'Lets Go 4'],
            ['id' => 285, 'name' => 'BW Jeez weekly 20'],
            ['id' => 286, 'name' => 'Corruption Cup Qualification Russia 1'],
            ['id' => 287, 'name' => 'EGM Fight Night 5'],
            ['id' => 288, 'name' => 'BW Jeez weekly 21'],
            ['id' => 289, 'name' => 'Corruption Cup Qualification Russia 2'],
            ['id' => 290, 'name' => 'Lets Go 5'],
            ['id' => 291, 'name' => 'BW Jeez weekly 22'],
            ['id' => 292, 'name' => 'Corrupted EU Qualifier I'],
            ['id' => 293, 'name' => 'BWCL S48 W1'],
            ['id' => 294, 'name' => 'Corrupted Cup Poland 1'],
            ['id' => 295, 'name' => 'Corruption Cup Qualification Russia 3'],
            ['id' => 296, 'name' => 'BW Jeez weekly 23'],
            ['id' => 297, 'name' => 'Corrupted Cup Poland 2'],
            ['id' => 298, 'name' => 'BWCL S48 W2'],
            ['id' => 299, 'name' => 'Corrupted Cup 2019 Quali FSU1'],
            ['id' => 300, 'name' => 'Lets Go 6 The Final Eight'],
            ['id' => 301, 'name' => 'BW Jeez weekly 24'],
            ['id' => 302, 'name' => 'Corrupted Cup 2019 LatAM Qualifier 1'],
            ['id' => 303, 'name' => 'BWCL S48 W3'],
            ['id' => 304, 'name' => 'Corrupted EU Qualifier II'],
            ['id' => 305, 'name' => 'Corruption Cup Qualification FSU 2'],
            ['id' => 306, 'name' => 'Corrupted Cup 2019 NA Qualifiers 1'],
            ['id' => 307, 'name' => 'BW Jeez weekly 25'],
            ['id' => 308, 'name' => 'BWCL S48 W4'],
            ['id' => 309, 'name' => 'Corrupted Cup 2019 LatAM Qualifier 2'],
            ['id' => 310, 'name' => 'Corrupted Cup 2019 NA Qualifiers 2'],
            ['id' => 311, 'name' => 'Corruption Cup Qualification Russia 4'],
            ['id' => 312, 'name' => 'BW Jeez weekly 26'],
            ['id' => 313, 'name' => 'BWCL S48 W5'],
            ['id' => 314, 'name' => 'BWCL S48 W6'],
            ['id' => 315, 'name' => 'BW Jeez weekly 27'],
            ['id' => 316, 'name' => 'Corruption Cup Qualification Russia Challengers'],
            ['id' => 317, 'name' => 'Corruption Cup Qualification EU Challengers'],
            ['id' => 318, 'name' => 'NYC LAN 2019 1'],
            ['id' => 319, 'name' => 'RCC The Arena Week 22 ASL Edition'],
            ['id' => 320, 'name' => 'BWCL S48 W7'],
            ['id' => 321, 'name' => 'BW Jeez weekly 28'],
            ['id' => 322, 'name' => 'Corrupted Cup 2019 Polish Quali 3'],
            ['id' => 323, 'name' => 'BWCL S48 W8'],
            ['id' => 324, 'name' => 'BW Jeez weekly 29'],
            ['id' => 325, 'name' => 'Corrupted Cup 2019 Polish Quali 4'],
            ['id' => 326, 'name' => 'EGM Fight Night 6'],
            ['id' => 327, 'name' => 'BWCL S48 W9'],
            ['id' => 328, 'name' => 'BW Jeez weekly 30'],
            ['id' => 329, 'name' => 'Corrupted Cup 2019 Polish Quali 5'],
            ['id' => 330, 'name' => 'Corrupted Cup 2019 Polish Quali finals'],
            ['id' => 331, 'name' => 'BWCL S48 W10'],
            ['id' => 332, 'name' => 'BW Jeez weekly 31'],
            ['id' => 333, 'name' => 'BSL7 Ladder Tournament 3'],
            ['id' => 334, 'name' => 'BWCL S48 Playoffs'],
            ['id' => 335, 'name' => 'North American Summer Starleague Qualifiers 2019'],
            ['id' => 336, 'name' => 'North American Summer Starleague 2019'],
            ['id' => 337, 'name' => 'BW Jeez weekly 32'],
            ['id' => 338, 'name' => 'Costa Rica StarCraft League 1 W1'],
            ['id' => 339, 'name' => '1v1 Eternal Contest Tourney'],
            ['id' => 340, 'name' => 'BW Jeez weekly 33'],
            ['id' => 341, 'name' => 'Costa Rica StarCraft League 1 W2'],
            ['id' => 342, 'name' => 'BSL7 Ladder Tour 1'],
            ['id' => 343, 'name' => 'BW Jeez weekly 34'],
            ['id' => 344, 'name' => 'Costa Rica StarCraft League 1 W3'],
            ['id' => 345, 'name' => 'BSL7 Ladder Tournament 2'],
            ['id' => 346, 'name' => 'BW Jeez weekly 35'],
            ['id' => 347, 'name' => 'Costa Rica StarCraft League 1 W4'],
            ['id' => 348, 'name' => 'DreamHack Montreal 2019'],
            ['id' => 349, 'name' => 'BW Jeez weekly 36'],
            ['id' => 350, 'name' => '1v1 EBASH Tourney'],
            ['id' => 351, 'name' => 'Costa Rica StarCraft League 1 W5'],
            ['id' => 352, 'name' => 'BSL7 Proleague ro24'],
            ['id' => 353, 'name' => 'EGM Fight Night 7'],
            ['id' => 354, 'name' => 'BW Jeez weekly 37'],
            ['id' => 355, 'name' => 'Costa Rica StarCraft League 1 W6'],
            ['id' => 356, 'name' => 'BSL7 GosuLeague ro32'],
            ['id' => 357, 'name' => 'Shinhan Tank Proleague Season 2'],
            ['id' => 358, 'name' => 'BW Jeez weekly 38'],
            ['id' => 359, 'name' => 'Costa Rica StarCraft League 1 W7'],
            ['id' => 360, 'name' => 'BSL7 Proleague ro16'],
            ['id' => 361, 'name' => 'BW Jeez weekly 39'],
            ['id' => 362, 'name' => 'Costa Rica StarCraft League 1 W8'],
            ['id' => 363, 'name' => 'LA LAN 2019'],
            ['id' => 364, 'name' => 'BW Jeez weekly 40'],
            ['id' => 365, 'name' => 'Costa Rica StarCraft League 1 W9'],
            ['id' => 366, 'name' => 'BSL7 ChoboLeague ro40'],
            ['id' => 367, 'name' => 'RCG 2019 Corrupted Cup Finals Day 1'],
            ['id' => 368, 'name' => 'RCG 2019 Corrupted Cup Finals Day 2'],
            ['id' => 369, 'name' => 'Costa Rica StarCraft League 1 W10'],
            ['id' => 370, 'name' => 'BSL7 GosuLeague final bracket'],
            ['id' => 371, 'name' => 'BSL7 ChoboLeague ro16'],
            ['id' => 372, 'name' => 'NYC LAN 2019 2'],
            ['id' => 373, 'name' => 'BSL7 proleague final bracket'],
            ['id' => 374, 'name' => 'BW Jeez weekly 42'],
            ['id' => 375, 'name' => 'Costa Rica StarCraft League 1 W11'],
            ['id' => 376, 'name' => 'Costa Rica StarCraft League 1 finals'],
            ['id' => 377, 'name' => 'North American 2019 Autumn Starleague Qualifiers 1'],
            ['id' => 378, 'name' => 'North American 2019 Autumn Starleague Qualifiers 2'],
            ['id' => 379, 'name' => 'North American vAutumn Starleague Qualifiers 2'],
            ['id' => 380, 'name' => 'BWCL Season 49 W1'],
            ['id' => 381, 'name' => 'BW Jeez weekly 43'],
            ['id' => 382, 'name' => 'North American 2019 Autumn Starleague Qualifiers 3'],
            ['id' => 383, 'name' => 'North American 2019 Autumn Starleague Qualifiers 4'],
            ['id' => 384, 'name' => 'BWCL Season 49 W2'],
            ['id' => 385, 'name' => 'BW Jeez weekly 44'],
            ['id' => 386, 'name' => 'North American 2019 Autumn Starleague Qualifiers 5'],
            ['id' => 387, 'name' => 'Titanes Nation Wars 1 W1'],
            ['id' => 388, 'name' => 'North American Starleague 2 2019 ro16'],
            ['id' => 389, 'name' => 'BWCL Season 49 W3'],
            ['id' => 390, 'name' => 'Shinhan Tank Proleague Season 3'],
            ['id' => 391, 'name' => 'BW Jeez weekly 45'],
            ['id' => 392, 'name' => 'Titanes Nation Wars 1 W2'],
            ['id' => 393, 'name' => 'EGM Fight Night 8'],
            ['id' => 394, 'name' => 'BWCL Season 49 W4'],
            ['id' => 395, 'name' => 'BW Jeez weekly 46'],
            ['id' => 396, 'name' => 'Titanes Nation Wars 1 W3'],
            ['id' => 397, 'name' => 'North American Starleague 2 2019 ro8'],
            ['id' => 398, 'name' => 'BWCL Season 49 W5'],
            ['id' => 399, 'name' => 'BW Jeez weekly 47'],
            ['id' => 400, 'name' => 'BWCL Season 49 W6'],
            ['id' => 401, 'name' => 'Titanes Nation Wars 1 W4'],
            ['id' => 402, 'name' => 'BW Jeez weekly 48'],
            ['id' => 403, 'name' => 'Titanes Nation Wars 1 W5'],
            ['id' => 404, 'name' => 'BW Jeez weekly 49'],
            ['id' => 405, 'name' => 'BSL8 Ladder Gosu and Chobo 1 tournament'],
            ['id' => 406, 'name' => 'North American Starleague 2 2019 ro4'],
            ['id' => 407, 'name' => 'Have At You 29'],
            ['id' => 408, 'name' => 'BWCL Season 49 W7'],
            ['id' => 409, 'name' => 'BSL8 Ladder Open 1'],
            ['id' => 410, 'name' => 'Moscow LAN 2019'],
            ['id' => 411, 'name' => 'Titanes Nation Wars 1 W6'],
            ['id' => 412, 'name' => 'BSL8 Ladder Gosu and Chobo 2'],
            ['id' => 413, 'name' => 'North American Starleague 2 2019 finals'],
            ['id' => 414, 'name' => 'BWCL Season 49 W8'],
            ['id' => 415, 'name' => 'BW Jeez weekly 50'],
            ['id' => 416, 'name' => 'BSL8 Ladder Tournament Open 2'],
            ['id' => 417, 'name' => 'Titanes Nation Wars 1 W7'],
            ['id' => 418, 'name' => 'BSL8 Ladder Gosu and Chobo 3'],
            ['id' => 419, 'name' => 'Have At You 30'],
            ['id' => 420, 'name' => 'BW Jeez weekly 51'],
            ['id' => 421, 'name' => 'BSL8 Ladder Tournament Open 3'],
            ['id' => 422, 'name' => 'Defiler Tour 87'],
            ['id' => 423, 'name' => 'EGM Fight Night Holiday Tour'],
            ['id' => 424, 'name' => 'BW Jeez weekly 52'],
            ['id' => 425, 'name' => 'BSL8 Proleague Ro24'],
            ['id' => 426, 'name' => 'Have At You 31'],
            ['id' => 427, 'name' => 'Titanes Nation Wars 1 W10'],
            ['id' => 428, 'name' => 'BWCL Season 49 W9'],
            ['id' => 429, 'name' => 'BSL8 Gosuleague Ro32'],
            ['id' => 430, 'name' => 'Titanes Nation Wars 1 W11'],
            ['id' => 431, 'name' => 'BSL8 Proleague Ro16'],
            ['id' => 432, 'name' => 'Have At You 32'],
            ['id' => 433, 'name' => 'BWCL Season 49 W10'],
            ['id' => 434, 'name' => 'BW Jeez weekly 53'],
            ['id' => 435, 'name' => 'Titanes Nation Wars 1 W12'],
            ['id' => 436, 'name' => 'Hazelys Nut Cup 1'],
            ['id' => 437, 'name' => 'EGM Fight Night 9'],
            ['id' => 438, 'name' => 'BWCL Season 49 Semifinals'],
            ['id' => 439, 'name' => 'BWCL Season 49 playoffs'],
            ['id' => 440, 'name' => 'BW Jeez weekly 54'],
            ['id' => 441, 'name' => 'BSL8 Gosuleague Ro16'],
            ['id' => 442, 'name' => 'BSL8 Gosuleague WildCard tournament'],
            ['id' => 443, 'name' => 'Titanes Nation Wars 1 Playoffs'],
            ['id' => 444, 'name' => 'BSL8 Proleague Ro8'],
            ['id' => 445, 'name' => 'Have At You 33'],
            ['id' => 446, 'name' => 'BWCL Season 49 3rd place match'],
            ['id' => 447, 'name' => 'BWCL Season 49 Finals'],
            ['id' => 448, 'name' => 'BW Jeez weekly 55'],
            ['id' => 449, 'name' => 'Russian ProLeague Season 1 RO16'],
            ['id' => 450, 'name' => 'BW Jeez weekly 56'],
            ['id' => 451, 'name' => 'BSL8 Proleague Ro4'],
            ['id' => 452, 'name' => 'BSL8 Gosuleague Finals'],
            ['id' => 453, 'name' => 'Have At You 34'],
            ['id' => 454, 'name' => 'BSL8 Choboleague ro48'],
            ['id' => 455, 'name' => 'BW Jeez weekly 57'],
            ['id' => 456, 'name' => 'BSL8 Choboleague WildCard'],
            ['id' => 457, 'name' => 'BSL8 Proleague Finals'],
            ['id' => 458, 'name' => 'Russian ProLeague Season 1 RO8'],
            ['id' => 459, 'name' => 'Russian ProLeague Season 1 RO4'],
            ['id' => 460, 'name' => 'BW Jeez weekly 58'],
            ['id' => 461, 'name' => 'BSL8 Choboleague ro16'],
            ['id' => 462, 'name' => 'BSL8 Choboleague Finals'],
            ['id' => 463, 'name' => 'Have At You 35'],
            ['id' => 464, 'name' => 'BW Jeez weekly 59'],
            ['id' => 465, 'name' => 'Costa Rica StarCraft League 2'],
            ['id' => 466, 'name' => 'LA LAN 2 2020'],
            ['id' => 467, 'name' => 'Russian ProLeague Season 1 Finals'],
            ['id' => 468, 'name' => 'BW Jeez weekly 60'],
            ['id' => 469, 'name' => 'Have At You 36'],
            ['id' => 470, 'name' => 'BW Jeez weekly 61'],
            ['id' => 471, 'name' => 'BW Jeez weekly 62'],
            ['id' => 472, 'name' => 'BSL9 Ladder Open 1'],
            ['id' => 473, 'name' => 'Have At You 37'],
            ['id' => 474, 'name' => 'BSL9 Ladder Gosu  Chobo 1'],
            ['id' => 475, 'name' => 'BWCL Season 50 W1'],
            ['id' => 476, 'name' => 'BW Jeez weekly 63'],
            ['id' => 477, 'name' => 'TDR Liga Sudamericana Qualifier 1'],
            ['id' => 478, 'name' => 'BSL9 Ladder Open 2'],
            ['id' => 479, 'name' => 'TDR Liga Sudamericana Qualifier 2'],
            ['id' => 480, 'name' => 'BWCL Season 50 W2'],
            ['id' => 481, 'name' => 'BW Jeez weekly 64'],
            ['id' => 482, 'name' => 'BSL9 Nation Wars Americas vs Bolivia'],
            ['id' => 483, 'name' => 'BSL9 Nation Wars USA vs Europe'],
            ['id' => 484, 'name' => 'BSL9 Nation Wars Poland vs Sweden'],
            ['id' => 485, 'name' => 'BSL9 Nation Wars Russia vs Peru'],
            ['id' => 486, 'name' => 'BSL9 Nation Wars USA vs Americas'],
            ['id' => 487, 'name' => 'BSL9 Nation Wars Poland vs Peru'],
            ['id' => 488, 'name' => 'BSL9 Nation Wars Poland vs USA'],
            ['id' => 489, 'name' => 'TDR Liga Sudamericana Qualifier 3'],
            ['id' => 490, 'name' => 'Have At You 38'],
            ['id' => 491, 'name' => 'TDR Liga Sudamericana Qualifier 4'],
            ['id' => 492, 'name' => 'BWCL Season 50 W3'],
            ['id' => 493, 'name' => 'BW Jeez weekly 65'],
            ['id' => 494, 'name' => 'TDR Liga Sudamericana Wildcard Qualifier'],
            ['id' => 495, 'name' => 'BSL 9 ProLeague RO24'],
            ['id' => 496, 'name' => 'TDR South American Starleague RO16'],
            ['id' => 497, 'name' => 'BWCL Season 50 W4'],
            ['id' => 498, 'name' => 'BW Jeez weekly 66'],
            ['id' => 499, 'name' => 'Have At You 39'],
            ['id' => 500, 'name' => 'BSL 9 ProLeague RO16'],
            ['id' => 501, 'name' => 'BWCL Season 50 W5'],
            ['id' => 502, 'name' => 'BW Jeez weekly 67'],
            ['id' => 503, 'name' => 'BSL9 Gosu League Ro32'],
            ['id' => 504, 'name' => 'SCPH Brood War League'],
            ['id' => 505, 'name' => 'TDR South American Starleague RO8'],
            ['id' => 506, 'name' => 'BWCL Season 50 W6'],
            ['id' => 507, 'name' => 'BW Jeez weekly 68'],
            ['id' => 508, 'name' => 'BSL9 Ladder Gosu and Chobo 2'],
            ['id' => 509, 'name' => 'RCG 2020 Poland'],
            ['id' => 510, 'name' => 'Have at You 40'],
            ['id' => 511, 'name' => 'RCG 2020 Soviet Union'],
            ['id' => 512, 'name' => 'BWCL Season 50 W7'],
            ['id' => 513, 'name' => 'BW Jeez weekly 69'],
            ['id' => 514, 'name' => 'TDR South American Starleague RO4'],
            ['id' => 515, 'name' => 'TDR South American Starleague Finals'],
            ['id' => 516, 'name' => 'BSL 9 Gosu League ro16'],
            ['id' => 517, 'name' => 'BSL 9 ProLeague RO8'],
            ['id' => 518, 'name' => 'BWCL Season 50 W8'],
            ['id' => 519, 'name' => 'BW Jeez weekly 70'],
            ['id' => 520, 'name' => 'RCG 2020 Qualification North America '],
            ['id' => 521, 'name' => 'BSL 9 ChoboLeague ro16'],
            ['id' => 522, 'name' => 'Russian ProLeague Season 2 ro24'],
            ['id' => 523, 'name' => 'SC Remastered PH Ranked Players Tournament'],
            ['id' => 524, 'name' => 'Have at You 41'],
            ['id' => 525, 'name' => 'BWCL Season 50 W9'],
            ['id' => 526, 'name' => 'BW Jeez weekly 71'],
            ['id' => 527, 'name' => 'RCG 2020 Latin America'],
            ['id' => 528, 'name' => 'BSL9 Gosu League Ro8'],
            ['id' => 529, 'name' => 'BSL 9 ChoboLeague ro8'],
            ['id' => 530, 'name' => 'Russian ProLeague Season 2 ro16'],
            ['id' => 531, 'name' => 'RCG 2020 Europe Quali'],
            ['id' => 532, 'name' => 'BWCL Season 50 W10'],
            ['id' => 533, 'name' => 'BSL 9 ProLeague RO4'],
            ['id' => 534, 'name' => 'TDR North America vs South America'],
            ['id' => 535, 'name' => 'BSL 9 ChoboLeague ro4'],
            ['id' => 536, 'name' => 'BWCL Season 50 Playoffs'],
            ['id' => 537, 'name' => 'TDR NASL3 Qualifiers 1'],
            ['id' => 538, 'name' => 'BSL9 Gosu League Final'],
            ['id' => 539, 'name' => 'Have At You 42'],
            ['id' => 540, 'name' => 'RCG 2020 WorldWide Quali'],
            ['id' => 541, 'name' => 'TDR NASL3 Qualifiers 2'],
            ['id' => 542, 'name' => 'BWCL Season 50 W11'],
            ['id' => 543, 'name' => 'BW Jeez weekly 73'],
            ['id' => 544, 'name' => 'BSL 9 ChoboLeague Final'],
            ['id' => 545, 'name' => 'Russian ProLeague Season 2 ro8'],
            ['id' => 546, 'name' => 'TDR NASL3 Qualifiers 3'],
            ['id' => 547, 'name' => 'RCG 2020 Wild Card Quali'],
            ['id' => 548, 'name' => 'BWCL Season 50 W12'],
            ['id' => 549, 'name' => 'TDR NASL3 Qualifiers 4'],
            ['id' => 550, 'name' => 'BW Jeez weekly 74'],
            ['id' => 551, 'name' => 'Have At You 43'],
            ['id' => 552, 'name' => 'BW Jeez weekly 75'],
            ['id' => 553, 'name' => 'BWCL Season 50 W13'],
            ['id' => 554, 'name' => 'King of Kings 50'],
            ['id' => 555, 'name' => 'BWCL Season 50 W14'],
            ['id' => 556, 'name' => 'TDR North American Starleague 3'],
            ['id' => 557, 'name' => 'BW Jeez weekly 76'],
            ['id' => 558, 'name' => 'Costa Rica StarCraft League 2 Playoffs'],
            ['id' => 559, 'name' => 'Have At You 44'],
            ['id' => 560, 'name' => 'Bw Jeez Weekly 77'],
            ['id' => 561, 'name' => 'Bw Jeez weekly 78'],
            ['id' => 562, 'name' => 'TDR NAStier'],
            ['id' => 563, 'name' => 'BW Jeez weekly 79'],
            ['id' => 564, 'name' => 'Have At You 45'],
            ['id' => 565, 'name' => 'Tasteless vs Scarlett The Ultimate Challenge'],
            ['id' => 566, 'name' => 'nOm Monthly 1'],
            ['id' => 567, 'name' => 'BW Jeez Weekly 80'],
            ['id' => 568, 'name' => 'Have At You 46'],
            ['id' => 569, 'name' => 'BW Jeez Weekly 81'],
            ['id' => 570, 'name' => 'BWCL Season 51 W1'],
            ['id' => 571, 'name' => 'BWCL Season 51 W2'],
            ['id' => 572, 'name' => 'Ultimate Battle 2020 CadenZie vs Scarlett'],
            ['id' => 573, 'name' => 'Have At You 47'],
            ['id' => 574, 'name' => 'BWCL Season 51 W3'],
            ['id' => 575, 'name' => 'BW Jeez Weekly 82'],
            ['id' => 576, 'name' => 'TDR Nation Wars 2 W1'],
            ['id' => 577, 'name' => 'BSL10 Champions Tour'],
            ['id' => 578, 'name' => 'BWCL Season 51 W4'],
            ['id' => 579, 'name' => 'BW Jeez Weekly 83'],
            ['id' => 580, 'name' => 'Have At You 48'],
            ['id' => 581, 'name' => 'BSL10 Ladder Tour 1 Open '],
            ['id' => 582, 'name' => 'BW Jeez Weekly 84'],
            ['id' => 583, 'name' => 'BWCL Season 51 W5'],
            ['id' => 584, 'name' => 'BSL10 Race Wars 1'],
            ['id' => 585, 'name' => 'TDR Nation Wars 2 W2'],
            ['id' => 586, 'name' => 'BSL10 Ladder Gosu Chobo 1'],
            ['id' => 587, 'name' => 'BSL10 Ladder Open 2'],
            ['id' => 588, 'name' => 'BWCL Season 51 W6'],
            ['id' => 589, 'name' => 'BW Jeez Weekly 85'],
            ['id' => 590, 'name' => 'BSL10 Race Wars 2'],
            ['id' => 591, 'name' => 'TDR Nation Wars 2 W3'],
            ['id' => 592, 'name' => 'Have At You 49'],
            ['id' => 593, 'name' => 'BWCL Season 51 W7'],
            ['id' => 594, 'name' => 'BSL10 Last Chance Tour'],
            ['id' => 595, 'name' => 'BWCL Season 51 W8'],
            ['id' => 596, 'name' => 'BWCL Season 51 W9'],
            ['id' => 597, 'name' => 'TDR Nation Wars 2 W4'],
            ['id' => 598, 'name' => 'Tournament of the Legends'],
            ['id' => 599, 'name' => 'BSL 10 Proleague ro32'],
            ['id' => 600, 'name' => 'TDR Nation Wars 2 W5'],
            ['id' => 601, 'name' => 'BW Jeez Weekly 86'],
            ['id' => 602, 'name' => 'VOKA Retro Cup'],
            ['id' => 603, 'name' => 'BSL 10 Choboleague ro96'],
            ['id' => 604, 'name' => 'BW Jeez Weekly 87'],
            ['id' => 605, 'name' => 'TDR Nation Wars 2 W6'],
            ['id' => 606, 'name' => 'BSL 10 Gosuleague ro32'],
            ['id' => 607, 'name' => 'BSL 10 Proleague ro16'],
            ['id' => 608, 'name' => 'TDR Nation Wars 2 W7'],
            ['id' => 609, 'name' => 'BWCL Season 51 W10'],
            ['id' => 610, 'name' => 'BW Jeez weekly 88'],
            ['id' => 611, 'name' => 'BSL 10 Choboleague ro32'],
            ['id' => 612, 'name' => 'TDR Nation Wars 2 W8'],
            ['id' => 613, 'name' => 'BWCL Season 51 Playoffs'],
            ['id' => 614, 'name' => 'BW Jeez weekly 89'],
            ['id' => 615, 'name' => 'BSL 10 Gosuleague ro16'],
            ['id' => 616, 'name' => 'BSL 10 Proleague ro8'],
            ['id' => 617, 'name' => 'TDR Nation Wars 2 W9'],
            ['id' => 618, 'name' => 'BW Jeez weekly 90'],
            ['id' => 619, 'name' => 'BSL 10 Choboleague ro16'],
            ['id' => 620, 'name' => 'TDR Nation Wars 2 W10'],
            ['id' => 621, 'name' => 'BW Jeez weekly 91'],
            ['id' => 622, 'name' => 'BSL 10 GosuLeague Playoffs'],
            ['id' => 623, 'name' => 'BW Jeez weekly 92'],
            ['id' => 624, 'name' => 'TDR Nation Wars 2 W11'],
            ['id' => 625, 'name' => 'BSL 10 Chobleague Finals'],
            ['id' => 626, 'name' => 'BSL 10 Proleague Elimination Bracket'],
            ['id' => 627, 'name' => 'Turf Wars'],
            ['id' => 628, 'name' => 'BW Jeez weekly 93'],
            ['id' => 629, 'name' => 'BW Jeez weekly 94'],
            ['id' => 630, 'name' => 'TDR Nation Wars 2 Playoffs'],
            ['id' => 631, 'name' => 'Polish StarCraft League NOV 2020'],
            ['id' => 632, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin'],
            ['id' => 633, 'name' => 'Tasteless Showmatch Series 5'],
            ['id' => 634, 'name' => 'RCG 2020 World Finals Group Stage'],
            ['id' => 635, 'name' => 'BWCL Season 52 W1'],
            ['id' => 636, 'name' => 'TDR Nation Wars 2 Finals'],
            ['id' => 637, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W2'],
            ['id' => 638, 'name' => 'RCG 2020 World Finals RO8'],
            ['id' => 639, 'name' => 'BWCL Season 52 W2'],
            ['id' => 640, 'name' => 'RCG 2020 World Finals RO4'],
            ['id' => 641, 'name' => 'RCG 2020 Finals'],
            ['id' => 642, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W3'],
            ['id' => 643, 'name' => 'Artosis vs Scarlett Showmatch'],
            ['id' => 644, 'name' => 'BWCL Season 52 W3'],
            ['id' => 645, 'name' => 'BW Jeez weekly 98'],
            ['id' => 646, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W4'],
            ['id' => 647, 'name' => 'Polish StarCraft League 2'],
            ['id' => 648, 'name' => 'BWCL Season 52 W4'],
            ['id' => 649, 'name' => 'BW Jeez weekly 99'],
            ['id' => 650, 'name' => 'BW Jeez weekly 100'],
            ['id' => 651, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W5'],
            ['id' => 652, 'name' => 'BWCL Season 52 W5'],
            ['id' => 653, 'name' => 'BW Jeez weekly GF 2020'],
            ['id' => 654, 'name' => 'Peru StarCraft League 1 Ro16'],
            ['id' => 655, 'name' => 'BWCL Season 52 W6'],
            ['id' => 656, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W6'],
            ['id' => 657, 'name' => 'Polish StarCraft League 3'],
            ['id' => 658, 'name' => 'BWCL Season 52 W7'],
            ['id' => 659, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W7'],
            ['id' => 660, 'name' => 'BATTLE FOR AIUR'],
            ['id' => 661, 'name' => 'BSL11 Ladder Open 1'],
            ['id' => 662, 'name' => 'BWCL Season 52 W8'],
            ['id' => 663, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W8'],
            ['id' => 664, 'name' => 'BSL11 Ladder Chobo 1'],
            ['id' => 665, 'name' => 'Team Think Quick Best of the Best Tour W1'],
            ['id' => 666, 'name' => 'Rogue City Rumble ro16'],
            ['id' => 667, 'name' => 'BSL11 Ladder Open 2'],
            ['id' => 668, 'name' => 'BWCL Season 52 W9'],
            ['id' => 669, 'name' => 'Shinhan Tank Proleague Season 4 Round Robin W9'],
            ['id' => 670, 'name' => 'BSL11 Ladder Chobo 2'],
            ['id' => 671, 'name' => 'Team Think Quick Best of the Best Tour W2'],
            ['id' => 672, 'name' => 'BWCL Season 52 W10'],
            ['id' => 673, 'name' => 'Team Think Quick Best of the Best Tour W3'],
            ['id' => 674, 'name' => 'BSL11 Ladder Open 3'],
            ['id' => 675, 'name' => 'BWCL Season 52 W11'],
            ['id' => 676, 'name' => 'BSL11 Ro24'],
            ['id' => 677, 'name' => 'Team Think Quick Best of the Best Tour W4'],
            ['id' => 678, 'name' => 'Deathfate Pro League'],
            ['id' => 679, 'name' => 'BWCL Season 52 W12'],
            ['id' => 680, 'name' => 'BW Jeez weekly 101'],
            ['id' => 681, 'name' => 'Team Think Quick Best of the Best Tour W5'],
            ['id' => 682, 'name' => 'Rogue City Rumble'],
            ['id' => 683, 'name' => 'BSL11 Pro League Ro16'],
            ['id' => 684, 'name' => 'Shinhan Tank Proleague Season 4 Playoffs'],
            ['id' => 685, 'name' => 'BSL11 GosuLeague Ro32'],
            ['id' => 686, 'name' => 'Team Think Quick Best of the Best Tour W6'],
            ['id' => 687, 'name' => 'BW Jeez weekly 102'],
            ['id' => 688, 'name' => 'Team Think Quick Best of the Best Tour W7'],
            ['id' => 689, 'name' => 'BW Jeez weekly 103'],
            ['id' => 690, 'name' => 'BSL11 Pro League Playoffs'],
            ['id' => 691, 'name' => 'Ascension Rebirth Group A'],
            ['id' => 692, 'name' => 'Ascension Rebirth Group B'],
            ['id' => 693, 'name' => 'BSL11 GosuLeague Ro16'],
            ['id' => 694, 'name' => 'Ascension Rebirth Group C'],
            ['id' => 695, 'name' => 'Ascension Rebirth Final Group'],
            ['id' => 696, 'name' => 'Team Think Quick Best of the Best Tour W8'],
            ['id' => 697, 'name' => 'BW Jeez weekly 104'],
            ['id' => 698, 'name' => 'Peru StarCraft League 1 Playoffs'],
        ];

        DB::table('tournaments')->insert($data);
    }
}
