<?php

return [
    ['name' => 'Andorra', 'code' => 'AD', 'region' => 'Europe'],
    ['name' => 'United Arab Emirates', 'code' => 'AE', 'region' => 'Asia'],
    ['name' => 'Afghanistan', 'code' => 'AF', 'region' => 'Asia'],
    ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'region' => 'North America'],
    ['name' => 'Anguilla', 'code' => 'AI', 'region' => 'North America'],
    ['name' => 'Albania', 'code' => 'AL', 'region' => 'Europe'],
    ['name' => 'Armenia', 'code' => 'AM', 'region' => 'Asia'],
    ['name' => 'Angola', 'code' => 'AO', 'region' => 'Africa'],
    ['name' => 'Antarctica', 'code' => 'AQ', 'region' => 'Other'],
    ['name' => 'Argentina', 'code' => 'AR', 'region' => 'South America'],
    ['name' => 'American Samoa', 'code' => 'AS', 'region' => 'Oceania'],
    ['name' => 'Austria', 'code' => 'AT', 'region' => 'Europe'],
    ['name' => 'Australia', 'code' => 'AU', 'region' => 'Oceania'],
    ['name' => 'Aruba', 'code' => 'AW', 'region' => 'North America'],
    ['name' => 'Åland Islands', 'code' => 'AX', 'region' => 'Europe'],
    ['name' => 'Azerbaijan', 'code' => 'AZ', 'region' => 'Asia'],
    ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'region' => 'Europe'],
    ['name' => 'Barbados', 'code' => 'BB', 'region' => 'North America'],
    ['name' => 'Bangladesh', 'code' => 'BD', 'region' => 'Asia'],
    ['name' => 'Belgium', 'code' => 'BE', 'region' => 'Europe'],
    ['name' => 'Burkina Faso', 'code' => 'BF', 'region' => 'Africa'],
    ['name' => 'Bulgaria', 'code' => 'BG', 'region' => 'Europe'],
    ['name' => 'Bahrain', 'code' => 'BH', 'region' => 'Asia'],
    ['name' => 'Burundi', 'code' => 'BI', 'region' => 'Africa'],
    ['name' => 'Benin', 'code' => 'BJ', 'region' => 'Africa'],
    ['name' => 'Saint Barthélemy', 'code' => 'BL', 'region' => 'North America'],
    ['name' => 'Bermuda', 'code' => 'BM', 'region' => 'North America'],
    ['name' => 'Brunei', 'code' => 'BN', 'region' => 'Asia'],
    ['name' => 'Bolivia', 'code' => 'BO', 'region' => 'South America'],
    ['name' => 'Caribbean Netherlands', 'code' => 'BQ', 'region' => 'North America'],
    ['name' => 'Brazil', 'code' => 'BR', 'region' => 'South America'],
    ['name' => 'Bahamas', 'code' => 'BS', 'region' => 'North America'],
    ['name' => 'Bhutan', 'code' => 'BT', 'region' => 'Asia'],
    ['name' => 'Bouvet Island', 'code' => 'BV', 'region' => 'Other'],
    ['name' => 'Botswana', 'code' => 'BW', 'region' => 'Africa'],
    ['name' => 'Belarus', 'code' => 'BY', 'region' => 'Europe'],
    ['name' => 'Belize', 'code' => 'BZ', 'region' => 'North America'],
    ['name' => 'Canada', 'code' => 'CA', 'region' => 'North America'],
    ['name' => 'Cocos Islands', 'code' => 'CC', 'region' => 'Asia'],
    ['name' => 'DR Congo', 'code' => 'CD', 'region' => 'Africa'],
    ['name' => 'Central African Republic', 'code' => 'CF', 'region' => 'Africa'],
    ['name' => 'Congo', 'code' => 'CG', 'region' => 'Africa'],
    ['name' => 'Switzerland', 'code' => 'CH', 'region' => 'Europe'],
    ['name' => 'Ivory Coast', 'code' => 'CI', 'region' => 'Africa'],
    ['name' => 'Cook Islands', 'code' => 'CK', 'region' => 'Oceania'],
    ['name' => 'Chile', 'code' => 'CL', 'region' => 'South America'],
    ['name' => 'Cameroon', 'code' => 'CM', 'region' => 'Africa'],
    ['name' => 'China', 'code' => 'CN', 'region' => 'Asia'],
    ['name' => 'Colombia', 'code' => 'CO', 'region' => 'South America'],
    ['name' => 'Costa Rica', 'code' => 'CR', 'region' => 'North America'],
    ['name' => 'Cuba', 'code' => 'CU', 'region' => 'North America'],
    ['name' => 'Cape Verde', 'code' => 'CV', 'region' => 'Africa'],
    ['name' => 'Curaçao', 'code' => 'CW', 'region' => 'North America'],
    ['name' => 'Christmas Island', 'code' => 'CX', 'region' => 'Asia'],
    ['name' => 'Cyprus', 'code' => 'CY', 'region' => 'Europe'],
    ['name' => 'Czechia', 'code' => 'CZ', 'region' => 'Europe'],
    ['name' => 'Germany', 'code' => 'DE', 'region' => 'Europe'],
    ['name' => 'Djibouti', 'code' => 'DJ', 'region' => 'Africa'],
    ['name' => 'Denmark', 'code' => 'DK', 'region' => 'Europe'],
    ['name' => 'Dominica', 'code' => 'DM', 'region' => 'North America'],
    ['name' => 'Dominican Republic', 'code' => 'DO', 'region' => 'North America'],
    ['name' => 'Algeria', 'code' => 'DZ', 'region' => 'Africa'],
    ['name' => 'Ecuador', 'code' => 'EC', 'region' => 'South America'],
    ['name' => 'Estonia', 'code' => 'EE', 'region' => 'Europe'],
    ['name' => 'Egypt', 'code' => 'EG', 'region' => 'Africa'],
    ['name' => 'Western Sahara', 'code' => 'EH', 'region' => 'Africa'],
    ['name' => 'Eritrea', 'code' => 'ER', 'region' => 'Africa'],
    ['name' => 'Spain', 'code' => 'ES', 'region' => 'Europe'],
    ['name' => 'Ethiopia', 'code' => 'ET', 'region' => 'Africa'],
    ['name' => 'European Union', 'code' => 'EU', 'region' => 'Europe'],
    ['name' => 'Finland', 'code' => 'FI', 'region' => 'Europe'],
    ['name' => 'Fiji', 'code' => 'FJ', 'region' => 'Oceania'],
    ['name' => 'Falkland Islands', 'code' => 'FK', 'region' => 'South America'],
    ['name' => 'Micronesia', 'code' => 'FM', 'region' => 'Oceania'],
    ['name' => 'Faroe Islands', 'code' => 'FO', 'region' => 'Europe'],
    ['name' => 'France', 'code' => 'FR', 'region' => 'Europe'],
    ['name' => 'Gabon', 'code' => 'GA', 'region' => 'Africa'],
    ['name' => 'United Kingdom', 'code' => 'GB', 'region' => 'Europe'],
    ['name' => 'Grenada', 'code' => 'GD', 'region' => 'North America'],
    ['name' => 'Georgia', 'code' => 'GE', 'region' => 'Asia'],
    ['name' => 'French Guiana', 'code' => 'GF', 'region' => 'South America'],
    ['name' => 'Guernsey', 'code' => 'GG', 'region' => 'Europe'],
    ['name' => 'Ghana', 'code' => 'GH', 'region' => 'Africa'],
    ['name' => 'Gibraltar', 'code' => 'GI', 'region' => 'Europe'],
    ['name' => 'Greenland', 'code' => 'GL', 'region' => 'North America'],
    ['name' => 'Gambia', 'code' => 'GM', 'region' => 'Africa'],
    ['name' => 'Guinea', 'code' => 'GN', 'region' => 'Africa'],
    ['name' => 'Guadeloupe', 'code' => 'GP', 'region' => 'North America'],
    ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'region' => 'Africa'],
    ['name' => 'Greece', 'code' => 'GR', 'region' => 'Europe'],
    ['name' => 'South Georgia', 'code' => 'GS', 'region' => 'South America'],
    ['name' => 'Guatemala', 'code' => 'GT', 'region' => 'North America'],
    ['name' => 'Guam', 'code' => 'GU', 'region' => 'Oceania'],
    ['name' => 'Guinea-Bissau', 'code' => 'GW', 'region' => 'Africa'],
    ['name' => 'Guyana', 'code' => 'GY', 'region' => 'South America'],
    ['name' => 'Hong Kong', 'code' => 'HK', 'region' => 'Asia'],
    ['name' => 'Heard Island', 'code' => 'HM', 'region' => 'Other'],
    ['name' => 'Honduras', 'code' => 'HN', 'region' => 'North America'],
    ['name' => 'Croatia', 'code' => 'HR', 'region' => 'Europe'],
    ['name' => 'Haiti', 'code' => 'HT', 'region' => 'North America'],
    ['name' => 'Hungary', 'code' => 'HU', 'region' => 'Europe'],
    ['name' => 'Canary Islands', 'code' => 'IC', 'region' => 'Africa'],
    ['name' => 'Indonesia', 'code' => 'ID', 'region' => 'Asia'],
    ['name' => 'Ireland', 'code' => 'IE', 'region' => 'Europe'],
    ['name' => 'Israel', 'code' => 'IL', 'region' => 'Asia'],
    ['name' => 'Isle of Man', 'code' => 'IM', 'region' => 'Europe'],
    ['name' => 'India', 'code' => 'IN', 'region' => 'Asia'],
    ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'region' => 'Asia'],
    ['name' => 'Iraq', 'code' => 'IQ', 'region' => 'Asia'],
    ['name' => 'Iran', 'code' => 'IR', 'region' => 'Asia'],
    ['name' => 'Iceland', 'code' => 'IS', 'region' => 'Europe'],
    ['name' => 'Italy', 'code' => 'IT', 'region' => 'Europe'],
    ['name' => 'Jersey', 'code' => 'JE', 'region' => 'Europe'],
    ['name' => 'Jamaica', 'code' => 'JM', 'region' => 'North America'],
    ['name' => 'Jordan', 'code' => 'JO', 'region' => 'Asia'],
    ['name' => 'Japan', 'code' => 'JP', 'region' => 'Asia'],
    ['name' => 'Kenya', 'code' => 'KE', 'region' => 'Africa'],
    ['name' => 'Kyrgyzstan', 'code' => 'KG', 'region' => 'Asia'],
    ['name' => 'Cambodia', 'code' => 'KH', 'region' => 'Asia'],
    ['name' => 'Kiribati', 'code' => 'KI', 'region' => 'Oceania'],
    ['name' => 'Comoros', 'code' => 'KM', 'region' => 'Africa'],
    ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'region' => 'North America'],
    ['name' => 'North Korea', 'code' => 'KP', 'region' => 'Asia'],
    ['name' => 'South Korea', 'code' => 'KR', 'region' => 'Asia'],
    ['name' => 'Kuwait', 'code' => 'KW', 'region' => 'Asia'],
    ['name' => 'Cayman Islands', 'code' => 'KY', 'region' => 'North America'],
    ['name' => 'Kazakhstan', 'code' => 'KZ', 'region' => 'Asia'],
    ['name' => 'Laos', 'code' => 'LA', 'region' => 'Asia'],
    ['name' => 'Lebanon', 'code' => 'LB', 'region' => 'Asia'],
    ['name' => 'Saint Lucia', 'code' => 'LC', 'region' => 'North America'],
    ['name' => 'Liechtenstein', 'code' => 'LI', 'region' => 'Europe'],
    ['name' => 'Sri Lanka', 'code' => 'LK', 'region' => 'Asia'],
    ['name' => 'Liberia', 'code' => 'LR', 'region' => 'Africa'],
    ['name' => 'Lesotho', 'code' => 'LS', 'region' => 'Africa'],
    ['name' => 'Lithuania', 'code' => 'LT', 'region' => 'Europe'],
    ['name' => 'Luxembourg', 'code' => 'LU', 'region' => 'Europe'],
    ['name' => 'Latvia', 'code' => 'LV', 'region' => 'Europe'],
    ['name' => 'Libya', 'code' => 'LY', 'region' => 'Africa'],
    ['name' => 'Morocco', 'code' => 'MA', 'region' => 'Africa'],
    ['name' => 'Monaco', 'code' => 'MC', 'region' => 'Europe'],
    ['name' => 'Moldova', 'code' => 'MD', 'region' => 'Europe'],
    ['name' => 'Montenegro', 'code' => 'ME', 'region' => 'Europe'],
    ['name' => 'Saint Martin', 'code' => 'MF', 'region' => 'North America'],
    ['name' => 'Madagascar', 'code' => 'MG', 'region' => 'Africa'],
    ['name' => 'Marshall Islands', 'code' => 'MH', 'region' => 'Oceania'],
    ['name' => 'North Macedonia', 'code' => 'MK', 'region' => 'Europe'],
    ['name' => 'Mali', 'code' => 'ML', 'region' => 'Africa'],
    ['name' => 'Myanmar', 'code' => 'MM', 'region' => 'Asia'],
    ['name' => 'Mongolia', 'code' => 'MN', 'region' => 'Asia'],
    ['name' => 'Macau', 'code' => 'MO', 'region' => 'Asia'],
    ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'region' => 'Oceania'],
    ['name' => 'Martinique', 'code' => 'MQ', 'region' => 'North America'],
    ['name' => 'Mauritania', 'code' => 'MR', 'region' => 'Africa'],
    ['name' => 'Montserrat', 'code' => 'MS', 'region' => 'North America'],
    ['name' => 'Malta', 'code' => 'MT', 'region' => 'Europe'],
    ['name' => 'Mauritius', 'code' => 'MU', 'region' => 'Africa'],
    ['name' => 'Maldives', 'code' => 'MV', 'region' => 'Asia'],
    ['name' => 'Malawi', 'code' => 'MW', 'region' => 'Africa'],
    ['name' => 'Mexico', 'code' => 'MX', 'region' => 'North America'],
    ['name' => 'Malaysia', 'code' => 'MY', 'region' => 'Asia'],
    ['name' => 'Mozambique', 'code' => 'MZ', 'region' => 'Africa'],
    ['name' => 'Namibia', 'code' => 'NA', 'region' => 'Africa'],
    ['name' => 'New Caledonia', 'code' => 'NC', 'region' => 'Oceania'],
    ['name' => 'Niger', 'code' => 'NE', 'region' => 'Africa'],
    ['name' => 'Norfolk Island', 'code' => 'NF', 'region' => 'Oceania'],
    ['name' => 'Nigeria', 'code' => 'NG', 'region' => 'Africa'],
    ['name' => 'Nicaragua', 'code' => 'NI', 'region' => 'North America'],
    ['name' => 'Netherlands', 'code' => 'NL', 'region' => 'Europe'],
    ['name' => 'Norway', 'code' => 'NO', 'region' => 'Europe'],
    ['name' => 'Nepal', 'code' => 'NP', 'region' => 'Asia'],
    ['name' => 'Nauru', 'code' => 'NR', 'region' => 'Oceania'],
    ['name' => 'Niue', 'code' => 'NU', 'region' => 'Oceania'],
    ['name' => 'New Zealand', 'code' => 'NZ', 'region' => 'Oceania'],
    ['name' => 'Oman', 'code' => 'OM', 'region' => 'Asia'],
    ['name' => 'Panama', 'code' => 'PA', 'region' => 'North America'],
    ['name' => 'Peru', 'code' => 'PE', 'region' => 'South America'],
    ['name' => 'French Polynesia', 'code' => 'PF', 'region' => 'Oceania'],
    ['name' => 'Papua New Guinea', 'code' => 'PG', 'region' => 'Oceania'],
    ['name' => 'Philippines', 'code' => 'PH', 'region' => 'Asia'],
    ['name' => 'Pakistan', 'code' => 'PK', 'region' => 'Asia'],
    ['name' => 'Poland', 'code' => 'PL', 'region' => 'Europe'],
    ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'region' => 'North America'],
    ['name' => 'Pitcairn Islands', 'code' => 'PN', 'region' => 'Oceania'],
    ['name' => 'Puerto Rico', 'code' => 'PR', 'region' => 'North America'],
    ['name' => 'Palestine', 'code' => 'PS', 'region' => 'Asia'],
    ['name' => 'Portugal', 'code' => 'PT', 'region' => 'Europe'],
    ['name' => 'Palau', 'code' => 'PW', 'region' => 'Oceania'],
    ['name' => 'Paraguay', 'code' => 'PY', 'region' => 'South America'],
    ['name' => 'Qatar', 'code' => 'QA', 'region' => 'Asia'],
    ['name' => 'Réunion', 'code' => 'RE', 'region' => 'Africa'],
    ['name' => 'Romania', 'code' => 'RO', 'region' => 'Europe'],
    ['name' => 'Serbia', 'code' => 'RS', 'region' => 'Europe'],
    ['name' => 'Russia', 'code' => 'RU', 'region' => 'Europe'],
    ['name' => 'Rwanda', 'code' => 'RW', 'region' => 'Africa'],
    ['name' => 'Saudi Arabia', 'code' => 'SA', 'region' => 'Asia'],
    ['name' => 'Solomon Islands', 'code' => 'SB', 'region' => 'Oceania'],
    ['name' => 'Seychelles', 'code' => 'SC', 'region' => 'Africa'],
    ['name' => 'Sudan', 'code' => 'SD', 'region' => 'Africa'],
    ['name' => 'Sweden', 'code' => 'SE', 'region' => 'Europe'],
    ['name' => 'Singapore', 'code' => 'SG', 'region' => 'Asia'],
    ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'region' => 'Europe'],
    ['name' => 'Slovenia', 'code' => 'SI', 'region' => 'Europe'],
    ['name' => 'Slovakia', 'code' => 'SK', 'region' => 'Europe'],
    ['name' => 'Sierra Leone', 'code' => 'SL', 'region' => 'Africa'],
    ['name' => 'San Marino', 'code' => 'SM', 'region' => 'Europe'],
    ['name' => 'Senegal', 'code' => 'SN', 'region' => 'Africa'],
    ['name' => 'Somalia', 'code' => 'SO', 'region' => 'Africa'],
    ['name' => 'Suriname', 'code' => 'SR', 'region' => 'South America'],
    ['name' => 'South Sudan', 'code' => 'SS', 'region' => 'Africa'],
    ['name' => 'São Tomé and Príncipe', 'code' => 'ST', 'region' => 'Africa'],
    ['name' => 'El Salvador', 'code' => 'SV', 'region' => 'North America'],
    ['name' => 'Sint Maarten', 'code' => 'SX', 'region' => 'North America'],
    ['name' => 'Syria', 'code' => 'SY', 'region' => 'Asia'],
    ['name' => 'Eswatini', 'code' => 'SZ', 'region' => 'Africa'],
    ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'region' => 'North America'],
    ['name' => 'Chad', 'code' => 'TD', 'region' => 'Africa'],
    ['name' => 'French Southern Territories', 'code' => 'TF', 'region' => 'Other'],
    ['name' => 'Togo', 'code' => 'TG', 'region' => 'Africa'],
    ['name' => 'Thailand', 'code' => 'TH', 'region' => 'Asia'],
    ['name' => 'Tajikistan', 'code' => 'TJ', 'region' => 'Asia'],
    ['name' => 'Tokelau', 'code' => 'TK', 'region' => 'Oceania'],
    ['name' => 'Timor-Leste', 'code' => 'TL', 'region' => 'Asia'],
    ['name' => 'Turkmenistan', 'code' => 'TM', 'region' => 'Asia'],
    ['name' => 'Tunisia', 'code' => 'TN', 'region' => 'Africa'],
    ['name' => 'Tonga', 'code' => 'TO', 'region' => 'Oceania'],
    ['name' => 'Turkey', 'code' => 'TR', 'region' => 'Europe'],
    ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'region' => 'North America'],
    ['name' => 'Tuvalu', 'code' => 'TV', 'region' => 'Oceania'],
    ['name' => 'Taiwan', 'code' => 'TW', 'region' => 'Asia'],
    ['name' => 'Tanzania', 'code' => 'TZ', 'region' => 'Africa'],
    ['name' => 'Ukraine', 'code' => 'UA', 'region' => 'Europe'],
    ['name' => 'Uganda', 'code' => 'UG', 'region' => 'Africa'],
    ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'region' => 'Oceania'],
    ['name' => 'United Nations', 'code' => 'UN', 'region' => 'Other'],
    ['name' => 'United States', 'code' => 'US', 'region' => 'North America'],
    ['name' => 'Uruguay', 'code' => 'UY', 'region' => 'South America'],
    ['name' => 'Uzbekistan', 'code' => 'UZ', 'region' => 'Asia'],
    ['name' => 'Vatican City', 'code' => 'VA', 'region' => 'Europe'],
    ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'region' => 'North America'],
    ['name' => 'Venezuela', 'code' => 'VE', 'region' => 'South America'],
    ['name' => 'British Virgin Islands', 'code' => 'VG', 'region' => 'North America'],
    ['name' => 'U.S. Virgin Islands', 'code' => 'VI', 'region' => 'North America'],
    ['name' => 'Vietnam', 'code' => 'VN', 'region' => 'Asia'],
    ['name' => 'Vanuatu', 'code' => 'VU', 'region' => 'Oceania'],
    ['name' => 'Wallis and Futuna', 'code' => 'WF', 'region' => 'Oceania'],
    ['name' => 'Samoa', 'code' => 'WS', 'region' => 'Oceania'],
    ['name' => 'Kosovo', 'code' => 'XK', 'region' => 'Europe'],
    ['name' => 'Unknown', 'code' => 'XX', 'region' => 'Other'],
    ['name' => 'Yemen', 'code' => 'YE', 'region' => 'Asia'],
    ['name' => 'Mayotte', 'code' => 'YT', 'region' => 'Africa'],
    ['name' => 'South Africa', 'code' => 'ZA', 'region' => 'Africa'],
    ['name' => 'Zambia', 'code' => 'ZM', 'region' => 'Africa'],
    ['name' => 'Zimbabwe', 'code' => 'ZW', 'region' => 'Africa'],
];