<?php

namespace App\Models;

use App\Concerns\Traits\HasComments;
use App\Concerns\Traits\HasReactions;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use League\CommonMark\GithubFlavoredMarkdownConverter;

class Article extends Model
{

    use HasComments;
    use HasReactions;


    public const TYPE_UPDATE = 'update';
    public const TYPE_NEWS   = 'news';

    protected $fillable = [
        'type',
        'title',
        'slug',
        'body',
        'recalculation_report_id',
        'published_at',
    ];

    protected $casts = [
        'published_at' => 'datetime',
    ];

    /**
     * Render the markdown body to safe HTML.
     * GitHub-flavored markdown handles tables, autolinks, task lists, etc.
     */
    public function getBodyHtmlAttribute(): string
    {
        $converter = new GithubFlavoredMarkdownConverter([
            // Allow raw HTML so we can embed flags, race-colored race tags, and
            // other rich markup directly in markdown source. Articles are authored
            // by trusted admins (or generated by RecalculationReportService), so
            // there's no XSS surface from untrusted user input.
            'html_input'         => 'allow',
            'allow_unsafe_links' => false,
        ]);

        return (string) $converter->convert($this->body);
    }

    public function recalculationReport(): BelongsTo
    {
        return $this->belongsTo(RecalculationReport::class);
    }

    

    /**
     * Scope for articles that are publicly visible (have a published_at in the past).
     */
    public function scopePublished(Builder $query): Builder
    {
        return $query->whereNotNull('published_at')
                     ->where('published_at', '<=', now());
    }
}